site_name: CLIPipe
theme: readthedocs
repo_url: https://github.com/TartaricAcid/Mkdocs
copyright: shang_zhang@foxmail.com

nav:
    - Home: index.md
    - Chapter1: 
        - 1_chapter/1.1_11content.md
        - 1_chapter/1.2_12content.md
    - Chapter1: 
        - 1.1: 1_chapter/1.1_11content.md
        - 1.2: 1_chapter/1.2_12content.md
    - About: about.md